# We can use anyone CI/CD here like Git ci/cd or travis but as i dont have Pro version of travis at this point so im using githhub directly for testing purpose also

language: node_js
node_js:
  - "stable"

script:
  - npm install
  - npm test
  - npm run build

deploy:
  provider:surge
  skip_cleanup: true
  domain:melodic-cracker.surge.sh
  project: ./build/
on:
  branch: master