name: Deploying React Timer App (Test Drive Development)

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        
      - name: Install NodeJS
        uses: actions/setup-node@v2-beta
        with:
          node-version: 12
      
      - name: Install JS dependencies
        run: npm install




    
      - name: testing build
        run: npm test
    
      - name: Creating build
        run: npm run build
        env:
          CI: false

      - name: Install Surge
        run: npm install --global surge
        
      - name: Deploy to Surge
        run: surge ./build react-timer-app-faryaad-azim.surge.sh/ --token ${{ secrets.SURGE_TOKEN }}
