name: Deploying React Timer App (TDD)

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        
      - name: Install NodeJS
        uses: actions/setup-node@v2-beta
        with:
          node-version: 12
          
      - name: Install yarn
        run: npm install --global yarn
      
      - name: Install JS dependencies
        run: yarn install




    
      - name: Creating build
        run: yarn build
        env:
          CI: false

      - name: Install Surge
        run: npm install --global surge
        
      - name: Deploy to Surge
        run: surge ./build react-timer-app-faryaad-azim.surge.sh/ --token ${{ secrets.SURGE_TOKEN }}
